### ISSUE TITLE
Missing game binaries after running launcher

### ISSUE THREAD

**Issue by maxestorr** [jhagrid77/CDDA-Linux-Launcher#10]
I'm running the script on a Ubuntu machine, with i3-wm as my window manager. I can download releases from the official CataclysmDDA github and run them fine, but when I use your launcher and I try to run the resulting "cataclysm-launcher" in the game's directory, I get the following error:

`Couldn't find cataclysm game binary in /home/max/games/Cataclysm-DDA/
`

[Here's](https://pastebin.com/vvFENuQ5) a pastebin link containing everything that shows up in my terminal whilst running your launcher.

**Comment by jhagrid77** [comment]
Same as #9 
Can be fixed by downloading the new copy of `Cataclysm-Ubuntu-Launcher.sh` from the master branch and running. 
The problem came from a typo that I repeated for compiling, where instead of `CCACHE=1` it was `CCACHE-1`. You can either manually change these or download the fixed version.

**Comment by M1m1c11** [comment]
didn't work

**Comment by jhagrid77** [comment]
@M1m1c11 Unfortunately I'm not completely surprised. 

As mentioned within #14, I have not been able to find the time to actively maintain this project so it is at least partially out of date.
You MIGHT have some better luck with the `test` branch, though I can't promise anything at this time.
